wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.6.10
    start_time: 1629495390
    t:
      1:
      - 1
      4: 3.6.10
      5: 0.12.0
      8:
      - 2
      - 5
